name: BlackMarketSkull
version: '${project.version}'
main: ee.vinku.black.BlackMarketSkull
api-version: '1.20'
depend: [WorldGuard]
loadbefore:
  - WorldGuard
commands:
  blackmarketskull:
    description: "Base command for the BlackMarketSkull plugin"
    usage: [ BlackMarketSkull ]
    aliases: [ bm ]
    permission: BlackMarketSkull.command.bm
    permission-message: "You do not have the permission!"